export default [
    "Solomon Islands",
"South Georgia and the South Sandwich Islands",
"Anguilla",
"Bahamas",
"Costa Rica",
"Falkland Islands (Malvinas)",
"France",
"Guinea",
"United States of America",
"Bolivia",
"Bulgaria",
"Mali",
"Vanuatu",
"Sudan",
"Zimbabwe",
"Albania",
"Ecuador",
"Guernsey",
"New Zealand",
"Norway",
"Pakistan",
"Denmark",
"Ghana",
"Taiwan, Republic of China",
"Netherlands Antilles",
"Qatar",
"Belgium",
"Cambodia",
"Holy See (Vatican City State)",
"Hong Kong, SAR China",
"Northern Mariana Islands",
"United Kingdom",
"Djibouti",
"Malaysia",
"Niue",
"Uganda",
"Cyprus",
"French Southern Territories",
"Liechtenstein",
"Macao, SAR China",
"Tuvalu",
"ALA Aland Islands",
"Wallis and Futuna Islands",
"Zambia",
"Moldova",
"Saint-Barthélemy",
"Tunisia",
"Uruguay",
"Armenia",
"French Guiana",
"Hungary",
"Algeria",
"British Indian Ocean Territory",
"Mayotte",
"Montserrat",
"Uzbekistan",
"Romania",
"Saudi Arabia",
"Angola",
"Aruba",
"Dominica",
"Macedonia, Republic of",
"Tonga",
"Niger",
"Puerto Rico",
"American Samoa",
"Antarctica",
"Colombia",
"Jordan",
"Micronesia, Federated States of",
"Somalia",
"Western Sahara",
"Slovakia",
"Grenada",
"Kuwait",
"Myanmar",
"Namibia",
"Nicaragua",
"Pitcairn",
"Heard and Mcdonald Islands",
"Honduras",
"Saint-Martin (French part)",
"Tanzania, United Republic of",
"Bouvet Island",
"Chad",
"Papua New Guinea",
"Saint Pierre and Miquelon",
"Sao Tome and Principe",
"Belarus",
"Palestinian Territory",
"Botswana",
"Portugal",
"Saint Lucia",
"US Minor Outlying Islands",
"Gibraltar",
"Mongolia",
"Nigeria",
"Norfolk Island",
"Svalbard and Jan Mayen Islands",
"Lao PDR",
"Peru",
"Rwanda",
"Sierra Leone",
"Faroe Islands",
"Greenland",
"Guyana",
"Turkmenistan",
"Burundi",
"Nepal",
"New Caledonia",
"United Arab Emirates",
"Ukraine",
"Argentina",
"Jamaica",
"Saint Vincent and Grenadines",
"Monaco",
"Serbia",
"South Sudan",
"Congo (Brazzaville)",
"Korea (South)",
"Madagascar",
"Kyrgyzstan",
"Cayman Islands",
"Italy",
"Senegal",
"Seychelles",
"Tokelau",
"Bosnia and Herzegovina",
"Georgia",
"Indonesia",
"Poland",
"Suriname",
"Czech Republic",
"Saint Helena",
"South Africa",
"Swaziland",
"Yemen",
"Guadeloupe",
"Korea (North)",
"Cameroon",
"Kazakhstan",
"Malta",
"Philippines",
"Samoa",
"Belize",
"Brazil",
"Cook Islands",
"Greece",
"Mauritania",
"Thailand",
"Austria",
"Eritrea",
"Palau",
"Turkey",
"Paraguay",
"Benin",
"Congo (Kinshasa)",
"Luxembourg",
"Panama",
"Timor-Leste",
"China",
"El Salvador",
"Guam",
"Israel",
"Republic of Kosovo",
"Cape Verde",
"Egypt",
"Mozambique",
"Canada",
"Ireland",
"Tajikistan",
"Libya",
"Mexico",
"Kenya",
"Togo",
"Chile",
"French Polynesia",
"Saint Kitts and Nevis",
"Turks and Caicos Islands",
"Malawi",
"Afghanistan",
"Croatia",
"Fiji",
"Iceland",
"Lebanon",
"Bangladesh",
"Burkina Faso",
"Gambia",
"Latvia",
"Montenegro",
"Estonia",
"Martinique",
"Switzerland",
"Spain",
"Bahrain",
"Bhutan",
"Dominican Republic",
"Germany",
"Antigua and Barbuda",
"Australia",
"Bermuda",
"Marshall Islands",
"Barbados",
"Mauritius",
"Nauru",
"Azerbaijan",
"Central African Republic",
"San Marino",
"Virgin Islands, US",
"Kiribati",
"Morocco",
"Equatorial Guinea",
"Gabon",
"Maldives",
"Oman",
"Singapore",
"Iran, Islamic Republic of",
"Isle of Man",
"Liberia",
"Sri Lanka",
"Sweden",
"British Virgin Islands",
"Iraq",
"Lithuania",
"Côte d'Ivoire",
"Haiti",
"Réunion",
"Christmas Island",
"Cocos (Keeling) Islands",
"Guinea-Bissau",
"Jersey",
"Trinidad and Tobago",
"Viet Nam",
"Brunei Darussalam",
"Cuba",
"Ethiopia",
"Japan",
"Slovenia",
"Finland",
"Guatemala",
"India",
"Lesotho",
"Netherlands",
"Syrian Arab Republic (Syria)",
"Andorra",
"Comoros",
"Russian Federation",
"Venezuela (Bolivarian Republic)"];